class CfgWeapons
{
	class ItemCore;
	class HeadgearItem;
	class H_HelmetSpecB;
	class PBW_Helm2_fleck: ItemCore
	{
		dlc="PBW_Kleiderkammer";
		scope=2;
		author="PBW-Team";
		weaponPoolAvailable=1;
		displayName="$STR_M92Fleck_Gras_name";
		picture="\german_headgear\ui\pbw_fleckfoliage.paa";
		model="german_headgear\pbw_m92gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: HeadgearItem
		{
			mass=32;
			uniformmodel="german_headgear\pbw_m92gras.p3d";
			modelSides[]={3,1};
			allowedSlots[]={801,901,701,605};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=8;
					passThrough=0.5;
				};
			};
			hiddenSelections[]=
			{
				"camo1",
				"alpha",
				"nv_holder",
				"goggle_up",
				"goggle_down",
				"glass1",
				"glass2",
				"headset"
			};
		};
	};
	class PBW_Helm2_fleck_BU: PBW_Helm2_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Fleck_Gras_BU_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm2_fleck_BUD: PBW_Helm2_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Fleck_Gras_BUD_name";
		picture="\german_headgear\ui\pbw_fleckfoliage.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck: PBW_Helm2_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92Fleck_name";
		picture="\german_headgear\ui\pbw_fleck.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen: PBW_Helm2_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92Tropen_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck_BO: PBW_Helm1_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Fleck_BO_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck_BOD: PBW_Helm1_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Fleck_BOD_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen_BO: PBW_Helm2_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Tropen_BO_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen_BOD: PBW_Helm2_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Tropen_BOD_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck_BU: PBW_Helm1_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Fleck_BU_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck_BUD: PBW_Helm1_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Fleck_BUD_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen_BU: PBW_Helm2_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Tropen_BU_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen_BUD: PBW_Helm2_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Tropen_BUD_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm2_fleck_H: H_HelmetSpecB
	{
		dlc="PBW_Kleiderkammer";
		scope=2;
		author="PBW-Team";
		weaponPoolAvailable=1;
		displayName="$STR_M92Fleck_Gras_H_name";
		picture="\german_headgear\ui\pbw_fleckfoliage.paa";
		model="german_headgear\pbw_M92gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=32;
			uniformmodel="german_headgear\pbw_M92gras.p3d";
			modelSides[]={3,1};
			allowedSlots[]={801,901,701,605};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=8;
					passThrough=0.5;
				};
			};
			hiddenSelections[]=
			{
				"camo1",
				"alpha",
				"nv_holder",
				"goggle_up",
				"goggle_down",
				"glass1",
				"glass2",
				"headset"
			};
		};
	};
	class PBW_Helm2_fleck_HBU: PBW_Helm2_fleck_H
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Fleck_Gras_BU_H_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm2_fleck_HBUD: PBW_Helm2_fleck_H
	{
		scope=1;
		author="PBW-Team";
		weaponPoolAvailable=1;
		displayName="$STR_M92Fleck_Gras_BUD_H_name";
		picture="\german_headgear\ui\pbw_fleck.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck_H: PBW_Helm2_fleck_HBUD
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92Fleck_H_name";
		picture="\german_headgear\ui\pbw_fleck.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen_H: PBW_Helm1_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92Tropen_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck_HBO: PBW_Helm2_fleck_HBUD
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92Fleck_BO_H_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck_HBOD: PBW_Helm2_fleck_HBUD
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92Fleck_BOD_name";
		picture="\german_headgear\ui\pbw_fleck.paa";
		model="german_headgear\pbw_M92gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen_HBO: PBW_Helm1_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92Tropen_BO_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		model="german_headgear\pbw_M92gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen_HBOD: PBW_Helm1_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92Tropen_BOD_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		model="german_headgear\pbw_M92gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck_HBU: PBW_Helm2_fleck_HBUD
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Fleck_BU_H_name";
		picture="\german_headgear\ui\pbw_fleck.paa";
		model="german_headgear\pbw_M92gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_fleck_HBUD: PBW_Helm2_fleck_HBUD
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Fleck_BUD_H_name";
		picture="\german_headgear\ui\pbw_fleck.paa";
		model="german_headgear\pbw_M92gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen_HBU: PBW_Helm1_fleck_H
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Tropen_BU_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		model="german_headgear\pbw_M92gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm1_tropen_HBUD: PBW_Helm1_fleck_H
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M92Tropen_BUD_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		model="german_headgear\pbw_M92gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm3_fleck: PBW_Helm2_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92BlankFleck_name";
		picture="\german_headgear\ui\pbw_stahlfleck.paa";
		model="german_headgear\pbw_M92.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92stahlF_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
			uniformmodel="german_headgear\pbw_M92.p3d";
			hiddenSelections[]=
			{
				"camo1",
				"alpha",
				"nv_holder",
				"goggle_up",
				"goggle_down",
				"glass1",
				"glass2",
				"headset"
			};
		};
	};
	class PBW_Helm3_tropen: PBW_Helm3_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92BlankTropen_name";
		picture="\german_headgear\ui\pbw_stahltropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92stahlT_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm3_UN: PBW_Helm3_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M92BlankUN_name";
		picture="\german_headgear\ui\pbw_stahlUN.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92stahlUN_co.paa",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm6_fleck: PBW_Helm3_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71BlankFleck_name";
		picture="\german_headgear\ui\pbw_stahlfleck.paa";
		model="german_headgear\pbw_M71.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92stahlF_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
			uniformmodel="german_headgear\pbw_M71.p3d";
			hiddenSelections[]=
			{
				"camo1",
				"alpha",
				"nv_holder",
				"goggle_up",
				"goggle_down",
				"glass1",
				"glass2",
				"headset"
			};
		};
	};
	class PBW_Helm6_tropen: PBW_Helm6_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71BlankTropen_name";
		picture="\german_headgear\ui\pbw_stahltropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92stahlT_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_b828_fleck: PBW_Helm2_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_B828BlankFleck_name";
		picture="\german_headgear\ui\pbw_stahlfleck.paa";
		model="german_headgear\pbw_b828.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_b828f_co.paa",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
			uniformmodel="german_headgear\pbw_b828.p3d";
			hiddenSelections[]=
			{
				"camo1",
				"alpha",
				"nv_holder",
				"goggle_up",
				"goggle_down",
				"glass1",
				"glass2",
				"headset"
			};
		};
	};
	class PBW_b828_tropen: PBW_b828_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_B828BlankTropen_name";
		picture="\german_headgear\ui\pbw_stahltropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_b828t_co.paa",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm5_fleck: PBW_Helm2_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71FleckGras_name";
		picture="\german_headgear\ui\pbw_fleckfoliage.paa";
		model="german_headgear\pbw_M71gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
			uniformmodel="german_headgear\pbw_M71gras.p3d";
			hiddenSelections[]=
			{
				"camo1",
				"alpha",
				"nv_holder",
				"goggle_up",
				"goggle_down",
				"glass1",
				"glass2",
				"headset"
			};
		};
	};
	class PBW_Helm5_fleck_BU: PBW_Helm5_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_Gras_BU_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm5_fleck_BUD: PBW_Helm5_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_Gras_BUD_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck: PBW_Helm5_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71Fleck_name";
		picture="\german_headgear\ui\pbw_fleck.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen: PBW_Helm5_fleck
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71Tropen_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck_BO: PBW_Helm4_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_BO_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck_BOD: PBW_Helm4_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_BOD_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen_BO: PBW_Helm5_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Tropen_BO_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen_BOD: PBW_Helm5_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Tropen_BOD_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck_BU: PBW_Helm4_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_BU_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck_BUD: PBW_Helm4_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_BUD_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen_BU: PBW_Helm5_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Tropen_BU_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen_BUD: PBW_Helm5_fleck
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Tropen_BUD_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			""
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm5_fleck_H: PBW_Helm2_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71Fleck_Gras_H_name";
		picture="\german_headgear\ui\pbw_fleckfoliage.paa";
		model="german_headgear\pbw_M71gras.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"alpha",
			"nv_holder",
			"goggle_up",
			"goggle_down",
			"glass1",
			"glass2",
			"headset"
		};
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			uniformmodel="german_headgear\pbw_M71gras.p3d";
			hiddenSelections[]=
			{
				"camo1",
				"alpha",
				"nv_holder",
				"goggle_up",
				"goggle_down",
				"glass1",
				"glass2",
				"headset"
			};
		};
	};
	class PBW_Helm5_fleck_HBU: PBW_Helm5_fleck_H
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_Gras_BU_H_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm5_fleck_HBUD: PBW_Helm5_fleck_H
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_Gras_BUD_H_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"german_headgear\tex\pbw_foliage_co.paa",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck_H: PBW_Helm5_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71Fleck_H_name";
		picture="\german_headgear\ui\pbw_fleck.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen_H: PBW_Helm4_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71Tropen_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"",
			"",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck_HBO: PBW_Helm4_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71Fleck_BO_H_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck_HBOD: PBW_Helm4_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71Fleck_BOD_H_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen_HBO: PBW_Helm4_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71Tropen_BO_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen_HBOD: PBW_Helm4_fleck_H
	{
		scope=2;
		author="PBW-Team";
		displayName="$STR_M71Tropen_BOD_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"",
			"",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck_HBU: PBW_Helm4_fleck_H
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_BU_H_name";
		picture="\german_headgear\ui\pbw_fleck.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_fleck_HBUD: PBW_Helm4_fleck_H
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Fleck_BUD_H_name";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_fleck_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_black_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen_HBU: PBW_Helm4_fleck_H
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Tropen_BU_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"german_headgear\tex\pbw_revision_glass_clear_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
	class PBW_Helm4_tropen_HBUD: PBW_Helm4_fleck_H
	{
		scope=1;
		author="PBW-Team";
		displayName="$STR_M71Tropen_BUD_H_name";
		picture="\german_headgear\ui\pbw_tropen.paa";
		hiddenSelectionsTextures[]=
		{
			"german_headgear\tex\pbw_m92_tropen_co.paa",
			"",
			"german_headgear\tex\pbw_headgear_co.paa",
			"",
			"german_headgear\tex\pbw_revision_brown_co.paa",
			"german_headgear\tex\pbw_revision_glass_black_ca.paa",
			"",
			"german_headgear\tex\pbw_headset_co.paa"
		};
		class ItemInfo: ItemInfo
		{
		};
	};
};